Add Ukrainian and Russian translation.
custom-components/places pull request #159
Opened 2023-04-09 18:30 UTC by vlad36N

Add Ukrainian and Russian translation.

2023-04-10 22:38 UTC, Snuffy2 requested changes
Thanks! I do not speak either of these languages so I'll rely on you for their accuracy. There appear to be a couple of small formatting errors.

2023-04-10 22:38 UTC, Snuffy2 commented on custom_components/places/translations/ua.json
> +                    "show_time": "Показати час останнього оновлення в кінці стану "(з xx:yy)"",
There should be single quotes around the parenthesis

2023-04-10 22:38 UTC, Snuffy2 commented on custom_components/places/translations/ua.json
> +                    "show_time": "Показати час останнього оновлення в кінці стану "(з xx:yy)"",
There should be single quotes around the parenthesis

2023-04-10 22:38 UTC, Snuffy2 commented on custom_components/places/translations/ua.json
> +            "description": "Вашу наявну конфігурацію YAML було автоматично імпортовано в інтерфейс користувача.\in\Видаліть конфігурацію YAML Місця зі свого файлу configuration.yaml і перезапустіть H
The JSON linter doesn't like the two \ in the string. Not sure if this is actually correct or not though.

2023-04-10 22:38 UTC, Snuffy2 commented on custom_components/places/translations/ru.json
> +            "description": "Ваша существующая конфигурация YAML была автоматически импортирована в пользовательский интерфейс.\in\Удалите конфигурацию Places YAML из файла configuration.yaml и переза
The JSON linter doesn't like the two \ in the string. Not sure if this is actually correct or not though.

2023-04-11 06:46 UTC, vlad36N commented
Fixed. Sorry my bad.

2023-04-11 13:51 UTC, Snuffy2 requested changes

2023-04-11 13:51 UTC, Snuffy2 commented on custom_components/places/translations/ru.json
> +            "description": "Ваша существующая конфигурация YAML была автоматически импортирована в пользовательский интерфейс.\n\n\Удалите конфигурацию Places YAML из файла configuration.yaml и перез
Is the \У correct? It is making it appear as invalid JSON.

2023-04-12 07:05 UTC, vlad36N commented on custom_components/places/translations/ru.json
> +            "description": "Ваша существующая конфигурация YAML была автоматически импортирована в пользовательский интерфейс.\n\n\Удалите конфигурацию Places YAML из файла configuration.yaml и перез
Sorry

2023-04-12 13:08 UTC, Snuffy2 approved these changes

2023-04-13 01:22 UTC, merged